#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_SIEUTHI")]
	public partial class DB_SieuThiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertThuongHIeu(ThuongHIeu instance);
    partial void UpdateThuongHIeu(ThuongHIeu instance);
    partial void DeleteThuongHIeu(ThuongHIeu instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertCTNhomSanPhamKM(CTNhomSanPhamKM instance);
    partial void UpdateCTNhomSanPhamKM(CTNhomSanPhamKM instance);
    partial void DeleteCTNhomSanPhamKM(CTNhomSanPhamKM instance);
    partial void InsertNhomSanPhamKM(NhomSanPhamKM instance);
    partial void UpdateNhomSanPhamKM(NhomSanPhamKM instance);
    partial void DeleteNhomSanPhamKM(NhomSanPhamKM instance);
    partial void InsertKhuyenMai(KhuyenMai instance);
    partial void UpdateKhuyenMai(KhuyenMai instance);
    partial void DeleteKhuyenMai(KhuyenMai instance);
    #endregion
		
		public DB_SieuThiDataContext() : 
				base(global::DAL.Properties.Settings.Default.QL_SIEUTHIConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SieuThiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SieuThiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SieuThiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SieuThiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<ThuongHIeu> ThuongHIeus
		{
			get
			{
				return this.GetTable<ThuongHIeu>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<CTNhomSanPhamKM> CTNhomSanPhamKMs
		{
			get
			{
				return this.GetTable<CTNhomSanPhamKM>();
			}
		}
		
		public System.Data.Linq.Table<NhomSanPhamKM> NhomSanPhamKMs
		{
			get
			{
				return this.GetTable<NhomSanPhamKM>();
			}
		}
		
		public System.Data.Linq.Table<KhuyenMai> KhuyenMais
		{
			get
			{
				return this.GetTable<KhuyenMai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNCC;
		
		private string _TenNCC;
		
		private string _SDT;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _Website;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    #endregion
		
		public NhaCungCap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50)")]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NChar(50)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThuongHIeu")]
	public partial class ThuongHIeu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTH;
		
		private string _TenTH;
		
		private EntitySet<SanPham> _SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTHChanging(string value);
    partial void OnMaTHChanged();
    partial void OnTenTHChanging(string value);
    partial void OnTenTHChanged();
    #endregion
		
		public ThuongHIeu()
		{
			this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTH
		{
			get
			{
				return this._MaTH;
			}
			set
			{
				if ((this._MaTH != value))
				{
					this.OnMaTHChanging(value);
					this.SendPropertyChanging();
					this._MaTH = value;
					this.SendPropertyChanged("MaTH");
					this.OnMaTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTH", DbType="NVarChar(50)")]
		public string TenTH
		{
			get
			{
				return this._TenTH;
			}
			set
			{
				if ((this._TenTH != value))
				{
					this.OnTenTHChanging(value);
					this.SendPropertyChanging();
					this._TenTH = value;
					this.SendPropertyChanged("TenTH");
					this.OnTenTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuongHIeu_SanPham", Storage="_SanPhams", ThisKey="MaTH", OtherKey="MaTH")]
		public EntitySet<SanPham> SanPhams
		{
			get
			{
				return this._SanPhams;
			}
			set
			{
				this._SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.ThuongHIeu = this;
		}
		
		private void detach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.ThuongHIeu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private string _TenSP;
		
		private System.Nullable<decimal> _GiaBan;
		
		private System.Nullable<int> _SLTon;
		
		private System.Nullable<System.DateTime> _NgaySX;
		
		private System.Nullable<System.DateTime> _HSD;
		
		private string _KichCo;
		
		private string _MauSac;
		
		private string _MaLoai;
		
		private string _MaTH;
		
		private EntitySet<CTNhomSanPhamKM> _CTNhomSanPhamKMs;
		
		private EntityRef<ThuongHIeu> _ThuongHIeu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnGiaBanChanging(System.Nullable<decimal> value);
    partial void OnGiaBanChanged();
    partial void OnSLTonChanging(System.Nullable<int> value);
    partial void OnSLTonChanged();
    partial void OnNgaySXChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySXChanged();
    partial void OnHSDChanging(System.Nullable<System.DateTime> value);
    partial void OnHSDChanged();
    partial void OnKichCoChanging(string value);
    partial void OnKichCoChanged();
    partial void OnMauSacChanging(string value);
    partial void OnMauSacChanged();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnMaTHChanging(string value);
    partial void OnMaTHChanged();
    #endregion
		
		public SanPham()
		{
			this._CTNhomSanPhamKMs = new EntitySet<CTNhomSanPhamKM>(new Action<CTNhomSanPhamKM>(this.attach_CTNhomSanPhamKMs), new Action<CTNhomSanPhamKM>(this.detach_CTNhomSanPhamKMs));
			this._ThuongHIeu = default(EntityRef<ThuongHIeu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Money")]
		public System.Nullable<decimal> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLTon", DbType="Int")]
		public System.Nullable<int> SLTon
		{
			get
			{
				return this._SLTon;
			}
			set
			{
				if ((this._SLTon != value))
				{
					this.OnSLTonChanging(value);
					this.SendPropertyChanging();
					this._SLTon = value;
					this.SendPropertyChanged("SLTon");
					this.OnSLTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySX", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySX
		{
			get
			{
				return this._NgaySX;
			}
			set
			{
				if ((this._NgaySX != value))
				{
					this.OnNgaySXChanging(value);
					this.SendPropertyChanging();
					this._NgaySX = value;
					this.SendPropertyChanged("NgaySX");
					this.OnNgaySXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSD", DbType="DateTime")]
		public System.Nullable<System.DateTime> HSD
		{
			get
			{
				return this._HSD;
			}
			set
			{
				if ((this._HSD != value))
				{
					this.OnHSDChanging(value);
					this.SendPropertyChanging();
					this._HSD = value;
					this.SendPropertyChanged("HSD");
					this.OnHSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichCo", DbType="NVarChar(50)")]
		public string KichCo
		{
			get
			{
				return this._KichCo;
			}
			set
			{
				if ((this._KichCo != value))
				{
					this.OnKichCoChanging(value);
					this.SendPropertyChanging();
					this._KichCo = value;
					this.SendPropertyChanged("KichCo");
					this.OnKichCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauSac", DbType="NVarChar(50)")]
		public string MauSac
		{
			get
			{
				return this._MauSac;
			}
			set
			{
				if ((this._MauSac != value))
				{
					this.OnMauSacChanging(value);
					this.SendPropertyChanging();
					this._MauSac = value;
					this.SendPropertyChanged("MauSac");
					this.OnMauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NChar(10)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTH", DbType="NChar(10)")]
		public string MaTH
		{
			get
			{
				return this._MaTH;
			}
			set
			{
				if ((this._MaTH != value))
				{
					if (this._ThuongHIeu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTHChanging(value);
					this.SendPropertyChanging();
					this._MaTH = value;
					this.SendPropertyChanged("MaTH");
					this.OnMaTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_CTNhomSanPhamKM", Storage="_CTNhomSanPhamKMs", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<CTNhomSanPhamKM> CTNhomSanPhamKMs
		{
			get
			{
				return this._CTNhomSanPhamKMs;
			}
			set
			{
				this._CTNhomSanPhamKMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuongHIeu_SanPham", Storage="_ThuongHIeu", ThisKey="MaTH", OtherKey="MaTH", IsForeignKey=true)]
		public ThuongHIeu ThuongHIeu
		{
			get
			{
				return this._ThuongHIeu.Entity;
			}
			set
			{
				ThuongHIeu previousValue = this._ThuongHIeu.Entity;
				if (((previousValue != value) 
							|| (this._ThuongHIeu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThuongHIeu.Entity = null;
						previousValue.SanPhams.Remove(this);
					}
					this._ThuongHIeu.Entity = value;
					if ((value != null))
					{
						value.SanPhams.Add(this);
						this._MaTH = value.MaTH;
					}
					else
					{
						this._MaTH = default(string);
					}
					this.SendPropertyChanged("ThuongHIeu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTNhomSanPhamKMs(CTNhomSanPhamKM entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_CTNhomSanPhamKMs(CTNhomSanPhamKM entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTNhomSanPhamKM")]
	public partial class CTNhomSanPhamKM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhomSP;
		
		private string _MaSP;
		
		private EntityRef<SanPham> _SanPham;
		
		private EntityRef<NhomSanPhamKM> _NhomSanPhamKM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomSPChanging(string value);
    partial void OnMaNhomSPChanged();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    #endregion
		
		public CTNhomSanPhamKM()
		{
			this._SanPham = default(EntityRef<SanPham>);
			this._NhomSanPhamKM = default(EntityRef<NhomSanPhamKM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomSP", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomSP
		{
			get
			{
				return this._MaNhomSP;
			}
			set
			{
				if ((this._MaNhomSP != value))
				{
					if (this._NhomSanPhamKM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomSPChanging(value);
					this.SendPropertyChanging();
					this._MaNhomSP = value;
					this.SendPropertyChanged("MaNhomSP");
					this.OnMaNhomSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_CTNhomSanPhamKM", Storage="_SanPham", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.CTNhomSanPhamKMs.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.CTNhomSanPhamKMs.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(string);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSanPhamKM_CTNhomSanPhamKM", Storage="_NhomSanPhamKM", ThisKey="MaNhomSP", OtherKey="MaNhomSP", IsForeignKey=true)]
		public NhomSanPhamKM NhomSanPhamKM
		{
			get
			{
				return this._NhomSanPhamKM.Entity;
			}
			set
			{
				NhomSanPhamKM previousValue = this._NhomSanPhamKM.Entity;
				if (((previousValue != value) 
							|| (this._NhomSanPhamKM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSanPhamKM.Entity = null;
						previousValue.CTNhomSanPhamKMs.Remove(this);
					}
					this._NhomSanPhamKM.Entity = value;
					if ((value != null))
					{
						value.CTNhomSanPhamKMs.Add(this);
						this._MaNhomSP = value.MaNhomSP;
					}
					else
					{
						this._MaNhomSP = default(string);
					}
					this.SendPropertyChanged("NhomSanPhamKM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomSanPhamKM")]
	public partial class NhomSanPhamKM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhomSP;
		
		private string _LoaiNhom;
		
		private EntitySet<CTNhomSanPhamKM> _CTNhomSanPhamKMs;
		
		private EntitySet<KhuyenMai> _KhuyenMais;
		
		private EntitySet<KhuyenMai> _KhuyenMais1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomSPChanging(string value);
    partial void OnMaNhomSPChanged();
    partial void OnLoaiNhomChanging(string value);
    partial void OnLoaiNhomChanged();
    #endregion
		
		public NhomSanPhamKM()
		{
			this._CTNhomSanPhamKMs = new EntitySet<CTNhomSanPhamKM>(new Action<CTNhomSanPhamKM>(this.attach_CTNhomSanPhamKMs), new Action<CTNhomSanPhamKM>(this.detach_CTNhomSanPhamKMs));
			this._KhuyenMais = new EntitySet<KhuyenMai>(new Action<KhuyenMai>(this.attach_KhuyenMais), new Action<KhuyenMai>(this.detach_KhuyenMais));
			this._KhuyenMais1 = new EntitySet<KhuyenMai>(new Action<KhuyenMai>(this.attach_KhuyenMais1), new Action<KhuyenMai>(this.detach_KhuyenMais1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomSP", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomSP
		{
			get
			{
				return this._MaNhomSP;
			}
			set
			{
				if ((this._MaNhomSP != value))
				{
					this.OnMaNhomSPChanging(value);
					this.SendPropertyChanging();
					this._MaNhomSP = value;
					this.SendPropertyChanged("MaNhomSP");
					this.OnMaNhomSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNhom", DbType="NVarChar(100)")]
		public string LoaiNhom
		{
			get
			{
				return this._LoaiNhom;
			}
			set
			{
				if ((this._LoaiNhom != value))
				{
					this.OnLoaiNhomChanging(value);
					this.SendPropertyChanging();
					this._LoaiNhom = value;
					this.SendPropertyChanged("LoaiNhom");
					this.OnLoaiNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSanPhamKM_CTNhomSanPhamKM", Storage="_CTNhomSanPhamKMs", ThisKey="MaNhomSP", OtherKey="MaNhomSP")]
		public EntitySet<CTNhomSanPhamKM> CTNhomSanPhamKMs
		{
			get
			{
				return this._CTNhomSanPhamKMs;
			}
			set
			{
				this._CTNhomSanPhamKMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSanPhamKM_KhuyenMai", Storage="_KhuyenMais", ThisKey="MaNhomSP", OtherKey="MaNhomSPMua")]
		public EntitySet<KhuyenMai> KhuyenMais
		{
			get
			{
				return this._KhuyenMais;
			}
			set
			{
				this._KhuyenMais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSanPhamKM_KhuyenMai1", Storage="_KhuyenMais1", ThisKey="MaNhomSP", OtherKey="MaNhomSPTang")]
		public EntitySet<KhuyenMai> KhuyenMais1
		{
			get
			{
				return this._KhuyenMais1;
			}
			set
			{
				this._KhuyenMais1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTNhomSanPhamKMs(CTNhomSanPhamKM entity)
		{
			this.SendPropertyChanging();
			entity.NhomSanPhamKM = this;
		}
		
		private void detach_CTNhomSanPhamKMs(CTNhomSanPhamKM entity)
		{
			this.SendPropertyChanging();
			entity.NhomSanPhamKM = null;
		}
		
		private void attach_KhuyenMais(KhuyenMai entity)
		{
			this.SendPropertyChanging();
			entity.NhomSanPhamKM = this;
		}
		
		private void detach_KhuyenMais(KhuyenMai entity)
		{
			this.SendPropertyChanging();
			entity.NhomSanPhamKM = null;
		}
		
		private void attach_KhuyenMais1(KhuyenMai entity)
		{
			this.SendPropertyChanging();
			entity.NhomSanPhamKM1 = this;
		}
		
		private void detach_KhuyenMais1(KhuyenMai entity)
		{
			this.SendPropertyChanging();
			entity.NhomSanPhamKM1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuyenMai")]
	public partial class KhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKM;
		
		private string _TenKM;
		
		private string _MaNhomSPMua;
		
		private string _MaNhomSPTang;
		
		private int _SLMua;
		
		private System.Nullable<int> _SLTang;
		
		private double _GiaGiam;
		
		private System.DateTime _NgayBD;
		
		private System.DateTime _NgayKT;
		
		private string _DonViGiam;
		
		private EntityRef<NhomSanPhamKM> _NhomSanPhamKM;
		
		private EntityRef<NhomSanPhamKM> _NhomSanPhamKM1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKMChanging(string value);
    partial void OnMaKMChanged();
    partial void OnTenKMChanging(string value);
    partial void OnTenKMChanged();
    partial void OnMaNhomSPMuaChanging(string value);
    partial void OnMaNhomSPMuaChanged();
    partial void OnMaNhomSPTangChanging(string value);
    partial void OnMaNhomSPTangChanged();
    partial void OnSLMuaChanging(int value);
    partial void OnSLMuaChanged();
    partial void OnSLTangChanging(System.Nullable<int> value);
    partial void OnSLTangChanged();
    partial void OnGiaGiamChanging(double value);
    partial void OnGiaGiamChanged();
    partial void OnNgayBDChanging(System.DateTime value);
    partial void OnNgayBDChanged();
    partial void OnNgayKTChanging(System.DateTime value);
    partial void OnNgayKTChanged();
    partial void OnDonViGiamChanging(string value);
    partial void OnDonViGiamChanged();
    #endregion
		
		public KhuyenMai()
		{
			this._NhomSanPhamKM = default(EntityRef<NhomSanPhamKM>);
			this._NhomSanPhamKM1 = default(EntityRef<NhomSanPhamKM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKM", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKM
		{
			get
			{
				return this._MaKM;
			}
			set
			{
				if ((this._MaKM != value))
				{
					this.OnMaKMChanging(value);
					this.SendPropertyChanging();
					this._MaKM = value;
					this.SendPropertyChanged("MaKM");
					this.OnMaKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKM", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenKM
		{
			get
			{
				return this._TenKM;
			}
			set
			{
				if ((this._TenKM != value))
				{
					this.OnTenKMChanging(value);
					this.SendPropertyChanging();
					this._TenKM = value;
					this.SendPropertyChanged("TenKM");
					this.OnTenKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomSPMua", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaNhomSPMua
		{
			get
			{
				return this._MaNhomSPMua;
			}
			set
			{
				if ((this._MaNhomSPMua != value))
				{
					if (this._NhomSanPhamKM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomSPMuaChanging(value);
					this.SendPropertyChanging();
					this._MaNhomSPMua = value;
					this.SendPropertyChanged("MaNhomSPMua");
					this.OnMaNhomSPMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomSPTang", DbType="VarChar(50)")]
		public string MaNhomSPTang
		{
			get
			{
				return this._MaNhomSPTang;
			}
			set
			{
				if ((this._MaNhomSPTang != value))
				{
					if (this._NhomSanPhamKM1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomSPTangChanging(value);
					this.SendPropertyChanging();
					this._MaNhomSPTang = value;
					this.SendPropertyChanged("MaNhomSPTang");
					this.OnMaNhomSPTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLMua", DbType="Int NOT NULL")]
		public int SLMua
		{
			get
			{
				return this._SLMua;
			}
			set
			{
				if ((this._SLMua != value))
				{
					this.OnSLMuaChanging(value);
					this.SendPropertyChanging();
					this._SLMua = value;
					this.SendPropertyChanged("SLMua");
					this.OnSLMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLTang", DbType="Int")]
		public System.Nullable<int> SLTang
		{
			get
			{
				return this._SLTang;
			}
			set
			{
				if ((this._SLTang != value))
				{
					this.OnSLTangChanging(value);
					this.SendPropertyChanging();
					this._SLTang = value;
					this.SendPropertyChanged("SLTang");
					this.OnSLTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaGiam", DbType="Float NOT NULL")]
		public double GiaGiam
		{
			get
			{
				return this._GiaGiam;
			}
			set
			{
				if ((this._GiaGiam != value))
				{
					this.OnGiaGiamChanging(value);
					this.SendPropertyChanging();
					this._GiaGiam = value;
					this.SendPropertyChanged("GiaGiam");
					this.OnGiaGiamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBD", DbType="DateTime NOT NULL")]
		public System.DateTime NgayBD
		{
			get
			{
				return this._NgayBD;
			}
			set
			{
				if ((this._NgayBD != value))
				{
					this.OnNgayBDChanging(value);
					this.SendPropertyChanging();
					this._NgayBD = value;
					this.SendPropertyChanged("NgayBD");
					this.OnNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKT", DbType="DateTime NOT NULL")]
		public System.DateTime NgayKT
		{
			get
			{
				return this._NgayKT;
			}
			set
			{
				if ((this._NgayKT != value))
				{
					this.OnNgayKTChanging(value);
					this.SendPropertyChanging();
					this._NgayKT = value;
					this.SendPropertyChanged("NgayKT");
					this.OnNgayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViGiam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DonViGiam
		{
			get
			{
				return this._DonViGiam;
			}
			set
			{
				if ((this._DonViGiam != value))
				{
					this.OnDonViGiamChanging(value);
					this.SendPropertyChanging();
					this._DonViGiam = value;
					this.SendPropertyChanged("DonViGiam");
					this.OnDonViGiamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSanPhamKM_KhuyenMai", Storage="_NhomSanPhamKM", ThisKey="MaNhomSPMua", OtherKey="MaNhomSP", IsForeignKey=true)]
		public NhomSanPhamKM NhomSanPhamKM
		{
			get
			{
				return this._NhomSanPhamKM.Entity;
			}
			set
			{
				NhomSanPhamKM previousValue = this._NhomSanPhamKM.Entity;
				if (((previousValue != value) 
							|| (this._NhomSanPhamKM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSanPhamKM.Entity = null;
						previousValue.KhuyenMais.Remove(this);
					}
					this._NhomSanPhamKM.Entity = value;
					if ((value != null))
					{
						value.KhuyenMais.Add(this);
						this._MaNhomSPMua = value.MaNhomSP;
					}
					else
					{
						this._MaNhomSPMua = default(string);
					}
					this.SendPropertyChanged("NhomSanPhamKM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSanPhamKM_KhuyenMai1", Storage="_NhomSanPhamKM1", ThisKey="MaNhomSPTang", OtherKey="MaNhomSP", IsForeignKey=true)]
		public NhomSanPhamKM NhomSanPhamKM1
		{
			get
			{
				return this._NhomSanPhamKM1.Entity;
			}
			set
			{
				NhomSanPhamKM previousValue = this._NhomSanPhamKM1.Entity;
				if (((previousValue != value) 
							|| (this._NhomSanPhamKM1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSanPhamKM1.Entity = null;
						previousValue.KhuyenMais1.Remove(this);
					}
					this._NhomSanPhamKM1.Entity = value;
					if ((value != null))
					{
						value.KhuyenMais1.Add(this);
						this._MaNhomSPTang = value.MaNhomSP;
					}
					else
					{
						this._MaNhomSPTang = default(string);
					}
					this.SendPropertyChanged("NhomSanPhamKM1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
